#!/usr/bin/env python3

# Copyright (C) 2024  KA Wright

"""Test suite runner for the `libkw` project."""

from subprocess import Popen, PIPE

import script.lib.manifest as manifest

GREEN = "\u001b[32;1m"
RED = "\u001b[31;1m"
YELLOW = "\u001b[33m"
RESET = "\u001b[0m"

def main():
    Popen(["clear"]).wait()
    for testdir in manifest.tests:
        print(f"TEST SUITE - {testdir}:")
        passed = 0
        failed = 0
        testno = 1
        for test in manifest.tests[testdir]:
            print(f"    {testno}. {test}: ", end='')
            testno += 1
            proc = Popen([f'build/test/{testdir}/{test}'], stdout=PIPE, 
                stderr=PIPE)
            stdout, stderr = proc.communicate()
            if proc.returncode == 0:
                # TODO Opt -c/--disable-color
                if test.count("FAIL") == 0:
                    print(f"{GREEN}PASS{RESET}")
                    passed += 1
                else:
                    print(f"{RED}FAIL{RESET}")
                    failed += 1
            else:
                if test.count("FAIL") > 0:
                    print(f"{GREEN}PASS{RESET}")
                    passed += 1
                else:
                    print(f"{RED}FAIL{RESET}")
                    failed += 1
                if stderr:
                    print(
                        f"{YELLOW}        {str(stderr, 'utf-8').strip()}"
                        f"{RESET}")
        # TODO Color passed test count GREEN for 100%; RED otherwise
        print(f"{passed}/{passed+failed} tests passed")
        print("---")
    print("Done!")

if __name__ == "__main__":
    main()
